sudo: required

# default is ruby, we set python in case we need to do some
# advanced scripting in our setup of the C++ tests
language: python

matrix:
  include:
    - os: linux
      services: docker
      env:
        docker_img=gsauthof/fedora-cxx-devel:27
        CMAKE_BUILD_TYPE=Debug
      python: 3.5
    - os: linux
      env:
        CMAKE_BUILD_TYPE=Release
      python: 3.5
      compiler: clang

before_install:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/before_install.sh

install:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/install.sh

before_script:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/before_script.sh

script:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/script.sh


